language: elixir
services:
  - docker
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
      - wkhtmltopdf
      - docker-ce
elixir:
  - 1.8.1
otp_release:
  - 21.2.5
notifications:
  slack:
    rooms:
      - secure: "Qj93V1MXqbgjwldP/XmZDXMP94+lOKUmDuFs0ONYBs3yn3BaJTf0O5La1bUMFNBV/qW+DGZYvk+H1ON1v1E+jdBrPfZvRywoEdznh9IfJ62/uygGYx7aKe9Y2zc+2kYtn0W6ooebrZtpV6YWKA8t1e5k5UYIx0WnykiEevVwnT26ZbJcttskJrNc7sBIouf9JmQSaZyRiF/sN/BEYIA9rvLoirKw98YK/CNUbeNOp6Kb4EZWYY2CFt3gOY9zXGYccQsc/PQvcZ6djs4yrds0aaqcTQCymRioqkdSMaHnvD2CS/cs6y4Cg2iFH9QYDpf45tn2aQkM0dMmVgeym08p0nz1uKWNC9ZaTmTXIodFgEeTK2kouBJOG0sJje0PXDp6S6g/v8FyB0zzCuOn5MrG0bkz5laCiR3s2HKWuWPRB7PTbhXCSLu9a1doXtKOAyFBwJoQRV/JcqMyh4Bm78jJvwSziUXU/Noiev/dspHbUiXUswfJXbXP0obRRp9CDyYRAORxXiL8j4onznjPOgXK8CfIZlD7Sikukqc4MsZuev4PEhJOlRommHvM9SASz+IpWQIVEN5hjabddxRnVXJqVIbfbRH2gTBJvOJ81aeciP5UDKjWrrRuhqgRW55roiHk6QXoq2GnMT4EzMy4sCGHIxm1QFMuBncAnKVDdAqDjpE="
    on_success: always
env:
  global:
    - DOCKER_NAMESPACE=edenlabllc
    - POSTGRES_VERSION=9.6
    - MIX_ENV=test
    - APPS='[{"app":"man_api","label":"api","namespace":"man","chart":"man", "deployment":"api"}]'
    # Docker
    - secure: "Id4bFepqJMkBGKTbQQXTpu6qUpygpsOHt/9jMSiwANmYnHp9tKZLNMl6HXRvcdS4wxSjeaaySm/QBAlp6JX8a9pOXL28CveXASa6ac3pAMj6G5qjGtVm3kSBfb4qHSDIFTUy2uiD8+gHZDmMJ6mtGbn/Sac3FQA5k5dRpuj/BcAMkQqYFe3zOrp9mvH6ojOYK9vH+b8UjhkUyJwBHHyYbVPr3DrKlsvlN/W031f6zYc112bDqMqeekDyGKVPfLsfy0mbUshfCG32gdDFM0jtq+KupDMDOtgsIzeef00oBp6pLNbLB35JV9nld05p7FIuz+v/gv4AvANIVkZrY97IezEGVqwAfuO3h4GgM51O9E3Ub1XI/5Dgn1FQJYwAAsgetd4mcZO7s0ktMuujG/YSu0pExzX69lavuq0q/X9cXiBtRVuS2iXfiXqa8qJkVVhkt5KRCLaDWl7W0jADTHNAM/Bu5ISxhfHd3tVxNJwcxhOW4pS8dcAQ3NFhj/Kd9Hv+hvXHBU0VSaPbczCApNetgureVWkkgv0Bgwy6aMNLuN5rQ6mxAgeh9Gu9q+6j1IuQAnim00FPIftEsIPsEefU3ZQnMMkVMEN2404rji3SEwNEmgljXW60bZGSgQncghr6gQk2ADzAYdidg8FZY4ymQ0tIij6ATPirX/vWLt9DAzQ="
branches:
  # Releases are generated automatically, stop infinite build loop
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  - sudo apt-get install jq
  - curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/init-db.sh -o init-db.sh; sudo sh ./init-db.sh
jobs:
  include:
    - stage: "test and build"
      name: "test"
      # run tests
      script:
      - "export DISPLAY=:99.0"
      - "sh -e /etc/init.d/xvfb start"
      - (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/tests.sh -o tests.sh; bash ./tests.sh) || travis_terminate 1
    - stage: "test and build"
      name: "man_api"
      env:
        - DB_MIGRATE=true
        - APPS='[{"app":"man_api","label":"api","namespace":"man","chart":"man", "deployment":"api"}]'
      # "Decrypting deploy key..."
      script:
      - openssl aes-256-cbc -K $encrypted_f6587fe9614b_key -iv $encrypted_f6587fe9614b_iv -in eHealth-8110bd102a69.json.enc -out eHealth-8110bd102a69.json -d
      - (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/docker.sh -o docker.sh; bash ./docker.sh) || travis_terminate 1
