language: elixir
services:
  - docker
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
      - wkhtmltopdf
      - docker-ce
elixir:
  - 1.7.4
otp_release:
  - 21.1.3
notifications:
  slack:
    rooms:
      - secure: "X1blJFdb5wpHSOinf25Do2JeOSHJZKH4mi+tjgdllABOFVi0bQpsiUa2DeMNeZ11mYuiwur48IPkpVJI/CjgLiZxGldrRwp+7zav0WXB6kLcWgK2dR1I1f9qhWOAojAnbnzcQ/kKCYJ2GGnA+mO/Pf6yi+qYaJVjkMZTr0QxKFXHx8+4X7lLJkw9r1C2Q0KlgwQ08hrLjXG3a77+dnc214aMN3Y8z9pDaqwx5szHEkHV/uJVWJSPiQD3xQRhEpadS5SykOAxlIzggPvDpplW+xcUmvVl5RtEw9RXJ+0/nwNwauexzk9Xj3RKYv0tt5QFubQRY7WhbijTabtS8Gp6Mvle4CohV2IbAhK7byRJ+iJ4Abmi4taz/iPBIlRESvK1NeX1Dn+EpznWRd1LvUnK/G6j2M0W2/tnn3XCl0IcWbtsL4oEeH4aXIDI8o3FQ1nhbe0WzfuLcC5JrSzp80zbWvidOR3J7LzKBGj+id2eMNN+uEf/eOiuP0FylJbxLBsLA5fIIbdkkDmRd9VtgfAI05FeHSCbHCnpBfuOGrRHU61DroYsGUkvFI+ZTuCVT6nKpSKfwyxYkaPpr3FUy4hNFvS2C3Noj4JVrkfbAGIw336e84PO4lfnwwjW9AefpgD6SMNu7q0x3dyRMjTWJpSQbdJQOZJMRmuU3q9uwIBafCw="
    on_success: always
env:
  global:
    - DOCKER_NAMESPACE=edenlabllc
    - POSTGRES_VERSION=9.6
    - MIX_ENV=test
    - APPS='[{"app":"man_api","label":"api","namespace":"man","chart":"man", "deployment":"api"}]'
    # Docker
    - secure: "Id4bFepqJMkBGKTbQQXTpu6qUpygpsOHt/9jMSiwANmYnHp9tKZLNMl6HXRvcdS4wxSjeaaySm/QBAlp6JX8a9pOXL28CveXASa6ac3pAMj6G5qjGtVm3kSBfb4qHSDIFTUy2uiD8+gHZDmMJ6mtGbn/Sac3FQA5k5dRpuj/BcAMkQqYFe3zOrp9mvH6ojOYK9vH+b8UjhkUyJwBHHyYbVPr3DrKlsvlN/W031f6zYc112bDqMqeekDyGKVPfLsfy0mbUshfCG32gdDFM0jtq+KupDMDOtgsIzeef00oBp6pLNbLB35JV9nld05p7FIuz+v/gv4AvANIVkZrY97IezEGVqwAfuO3h4GgM51O9E3Ub1XI/5Dgn1FQJYwAAsgetd4mcZO7s0ktMuujG/YSu0pExzX69lavuq0q/X9cXiBtRVuS2iXfiXqa8qJkVVhkt5KRCLaDWl7W0jADTHNAM/Bu5ISxhfHd3tVxNJwcxhOW4pS8dcAQ3NFhj/Kd9Hv+hvXHBU0VSaPbczCApNetgureVWkkgv0Bgwy6aMNLuN5rQ6mxAgeh9Gu9q+6j1IuQAnim00FPIftEsIPsEefU3ZQnMMkVMEN2404rji3SEwNEmgljXW60bZGSgQncghr6gQk2ADzAYdidg8FZY4ymQ0tIij6ATPirX/vWLt9DAzQ="
branches:
  # Releases are generated automatically, stop infinite build loop
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  - sudo apt-get install jq
  - curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/init-db.sh -o init-db.sh; sudo sh ./init-db.sh
jobs:
  include:
    - stage: "test and build"
      name: "test"
      # run tests
      script:
      - "export DISPLAY=:99.0"
      - "sh -e /etc/init.d/xvfb start"
      - (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/tests.sh -o tests.sh; bash ./tests.sh) || travis_terminate 1
    - stage: "test and build"
      name: "man_api"
      env:
        - DB_MIGRATE=true
        - APPS='[{"app":"man_api","label":"api","namespace":"man","chart":"man", "deployment":"api"}]'
      # "Decrypting deploy key..."
      script:
      - openssl aes-256-cbc -K $encrypted_f6587fe9614b_key -iv $encrypted_f6587fe9614b_iv -in eHealth-8110bd102a69.json.enc -out eHealth-8110bd102a69.json -d
      - (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/docker.sh -o docker.sh; bash ./docker.sh) || travis_terminate 1
